### PR TITLE
Ambiguous import fix

### PR DESCRIPTION
**Pull request by gloriousCode**
# The issue
Reading our Gocryptotrader database readme there is the following instruction:
```
go get -u github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql
```
Upon running this command, you receive:
```
go: found github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql in github.com/thrasher-corp/sqlboiler/drivers v0.0.0-20200323025506-efb378b421f4
go get github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql: ambiguous import: found package github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql in multiple modules:
        github.com/thrasher-corp/sqlboiler v1.0.1-0.20191001234224-71e17f37a85e (C:\Users\gloriousCode\go\pkg\mod\github.com\thrasher-corp\sqlboiler@v1.0.1-0.20191001234224-71e17f37a85e\drivers\sqlboiler-psql)
        github.com/thrasher-corp/sqlboiler/drivers v0.0.0-20200323025506-efb378b421f4 (C:\Users\gloriousCode\go\pkg\mod\github.com\thrasher-corp\sqlboiler\drivers@v0.0.0-20200323025506-efb378b421f4\sqlboiler-psql)
```

Cloning the repo lead me to experience the same thing when attempting to build. I've also attempted to do both with `GO111MODULE=off`

# The fix
The only way I was able to fix this was to get sqlboiler drivers to build was by modifying `go.mod` to build from local. However, there's not much information regarding ambiguous imports and am very open to feedback to fix this if there is a more proper way to fix this! I also just ran `go mod tidy`

Following my changes, I was able to run a `go build` and `go install` successfully, allowing me to continue adding database entries for postgres (sqlite was fine)

### CODE REVIEW

**Comment by xtda** [comment]
github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql is a binary helper that sqlboiler uses to generate models and it should should not be included as a dependancy for gocryptotrader 

this is why its included as part of a prerequisites and not in gct's module dependancies

**Comment by gloriousCode** [comment]
This PR does not add it as a dependency? I'm afraid I don't understand. Running the command found in our documentation cannot install the binary helper

**Comment by xtda** [comment]
go get will add it as a dependency if detects you are running the command within a path that already has an existing go module initialised (e.g if you run  go get -u github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql from within the gocryptotrader)

are you trying to run the command from within the gocryptotrader folder?

```
go help module-get
```
https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more

Have more information on using go get with go modules

**Comment by gloriousCode** [comment]
From anywhere, even without go a module intialised as well as with go modules turned off:
```
C:\>go get -u github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql
go: found github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql in github.com/thrasher-corp/sqlboiler/drivers v0.0.0-20200323025506-efb378b421f4
go: finding module for package github.com/pkg/errors
go: finding module for package github.com/thrasher-corp/sqlboiler/strmangle
go: finding module for package github.com/lib/pq
go: finding module for package github.com/thrasher-corp/sqlboiler/importers
go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1
go: found github.com/thrasher-corp/sqlboiler/importers in github.com/thrasher-corp/sqlboiler v3.5.0+incompatible
go: found github.com/lib/pq in github.com/lib/pq v1.8.0
go get github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql: ambiguous import: found package github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql in multiple modules:
        github.com/thrasher-corp/sqlboiler v3.5.0+incompatible (C:\Users\gloriousCode\go\pkg\mod\github.com\thrasher-corp\sqlboiler@v3.5.0+incompatible\drivers\sqlboiler-psql)
        github.com/thrasher-corp/sqlboiler/drivers v0.0.0-20200323025506-efb378b421f4 (C:\Users\gloriousCode\go\pkg\mod\github.com\thrasher-corp\sqlboiler\drivers@v0.0.0-20200323025506-efb378b421f4\sqlboiler-psql)
```

**Comment by xtda** [comment]
on a fresh go install on windows not having any issues

```powershell
❯ ls C:\users\andre\go\bin\


    Directory: C:\Users\andre\go\bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           2/06/2020 11:26 PM       18658304 dlv.exe
-a---           2/06/2020 11:25 PM        7033856 fillstruct.exe
-a---          30/04/2020 11:28 AM       15577088 gdlv.exe
-a---           2/06/2020 11:25 PM       13088768 gocode.exe
-a---           2/06/2020 11:26 PM       12632064 gocode-gomod.exe
-a---           2/06/2020 11:26 PM        9001984 godef.exe
-a---           2/06/2020 11:25 PM        8286208 godoctor.exe
-a---           2/06/2020 11:26 PM        6101504 goimports.exe
-a---           2/06/2020 11:26 PM        6540800 golint.exe
-a---           2/06/2020 11:25 PM        4894720 gomodifytags.exe
-a---          20/07/2020 10:13 PM        4805120 go-outline.exe
-a---          20/07/2020 10:13 PM        5697536 gopkgs.exe
-a---           2/06/2020 11:25 PM        7298048 goplay.exe
-a---          20/07/2020 10:13 PM       21877760 gopls.exe
-a---           2/06/2020 11:26 PM       21587456 gopls.exe~
-a---           2/06/2020 11:25 PM        6535168 gorename.exe
-a---          20/07/2020 10:13 PM        4596736 go-symbols.exe
-a---           2/06/2020 11:25 PM       13069312 gotests.exe
-a---          20/07/2020 10:13 PM        9746432 guru.exe
-a---           2/06/2020 11:25 PM        6296576 impl.exe


~
❯ get-command sqlboiler-psql.exe
Get-Command: The term 'sqlboiler-psql.exe' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

~
❯ go get -u github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql

~ took 20s
❯ get-command sqlboiler-psql.exe

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     sqlboiler-psql.exe                                 0.0.0.0    C:\Users\andre\go\bin\sqlboiler-psql.exe


~
❯
```

the only way i can get this to happen is by trying to go get within an existing module

```powershell
thrashercorp/codetests/boilertest via 🐹 v1.14.7
❯ go get -u github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql
go: downloading github.com/thrasher-corp/sqlboiler v1.0.0
go: downloading github.com/thrasher-corp/sqlboiler/drivers v0.0.0-20200323025506-efb378b421f4
go: downloading github.com/thrasher-corp/sqlboiler v3.5.0+incompatible
go: found github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql in github.com/thrasher-corp/sqlboiler/drivers v0.0.0-20200323025506-efb378b421f4
go: finding module for package github.com/lib/pq
go: finding module for package github.com/thrasher-corp/sqlboiler/strmangle
go: finding module for package github.com/thrasher-corp/sqlboiler/importers
go: finding module for package github.com/pkg/errors
go: downloading github.com/lib/pq v1.8.0
go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1
go: found github.com/thrasher-corp/sqlboiler/importers in github.com/thrasher-corp/sqlboiler v3.5.0+incompatible
go: found github.com/lib/pq in github.com/lib/pq v1.8.0
go get github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql: ambiguous import: found package github.com/thrasher-corp/sqlboiler/drivers/sqlboiler-psql in multiple modules:
        github.com/thrasher-corp/sqlboiler v3.5.0+incompatible (C:\Users\andre\go\pkg\mod\github.com\thrasher-corp\sqlboiler@v3.5.0+incompatible\drivers\sqlboiler-psql)
        github.com/thrasher-corp/sqlboiler/drivers v0.0.0-20200323025506-efb378b421f4 (C:\Users\andre\go\pkg\mod\github.com\thrasher-corp\sqlboiler\drivers@v0.0.0-20200323025506-efb378b421f4\sqlboiler-psql)
```

The problem with a relative path replace directive is it works under the assumption sqlboiler will always be located in the local path while 99% of the time this will be the case it breaks the idea behind go modules

**Comment by gloriousCode** [comment]
Nice! I'll investigate why it was happening for me in every directory without an existing go module tomorrow then

**Review by xtda — APPROVED** [review]
After some thought I am happy to have this merged if it fixes the issues you are having.
realistically this fork wont be used outside of gocryptotrader and anyone using it is going to either go get or clone the repo your fix works for both of those

After playing around on windows and macOS the only way i was able to get it to happen was inside a module again so i am thinking it might have something to do with gocryptorader having an old commit included breaking some mod cache

forcing a local directory will solve this so if everyone else is happy to proceed with it I am also happy

**Comment by gloriousCode** [comment]
So... I can get it to work sometimes as an administrator. Unfortunately, I cannot explain how. I also had it work when using a new Windows build. I will close this PR as my own Windows configuration does not count as an issue

**Pull request closed without merging**
